export const ActionTypes = {
    SELECTED_PRODUCT : 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT',
    ADD_TO_CART : 'ADD_TO_CART',
    FETCH_PRODUCTS_REQUEST : 'FETCH_API_REQUEST',
    FETCH_PRODUCTS_SUCCESS : 'FETCH_API_SUCCESS',
    FETCH_PRODUCTS_FAIL : 'FETCH_API_FAIL',
    SIGN_IN : 'SIGN_IN',
    SIGN_IN_ERR : 'SIGN_IN_ERR',
    SIGN_OUT : 'SIGN_OUT',
    SIGN_UP : 'SIGN_UP',
    SIGN_UP_ERR : 'SIGN_UP_ERR',
    ADD_FAVORITES : 'ADD_FAVORITES',
    ADD_FAVORITES_ERR : 'ADD_FAVORITES_ERR'
}